#!/bin/bash

echo "/mcp auth calendar"
echo "Chat"
echo ""
echo "/mcp auth chat"
echo "Drive"
echo ""
echo "/mcp auth drive"
echo "Gmail"
echo ""
echo "/mcp auth gmail"
echo "People"
echo ""
echo "/mcp auth people"
echo "Follow the prompts in your browser to authorize each service."
echo ""
echo "Verify Connection"
echo "Verify that the tools are loaded and ready:"
echo ""
echo "/mcp list"
